name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.5
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_sign_in: ^7.1.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.6.1
  lottie: ^3.3.1
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
