// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDodyiMDMU526TnqdFSfd-MZLk0aK_HuTY',
    appId: '1:381989125302:web:1c942629303df2ae343a17',
    messagingSenderId: '381989125302',
    projectId: 'kisiiecommerce',
    authDomain: 'kisiiecommerce.firebaseapp.com',
    storageBucket: 'kisiiecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATHsUKrlvfhruI3ks3jDQMpTrPOY2WQ1o',
    appId: '1:381989125302:android:c6a5f4c74d8158db343a17',
    messagingSenderId: '381989125302',
    projectId: 'kisiiecommerce',
    storageBucket: 'kisiiecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdKsWk5_-NUq653is9c9gBS6LVcKs1BmI',
    appId: '1:381989125302:ios:4777a1f3c46eb937343a17',
    messagingSenderId: '381989125302',
    projectId: 'kisiiecommerce',
    storageBucket: 'kisiiecommerce.appspot.com',
    androidClientId: '381989125302-t727tebgh63lb4np26oe303u4c05arip.apps.googleusercontent.com',
    iosClientId: '381989125302-pv07s4uqkfrq54dht5vc3pvarkuh96ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

}